=== AGranosik/pkck/Zadanie5/xml-parser/xml/lista_dysków.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:saps="http://example.com/saps"
           targetNamespace="http://example.com/saps">
    <xs:element name="dokument">
        <xs:complexType>
            <xs:sequence>


                <xs:element name="nagłówek">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="autorzy">
                                <xs:complexType>
                                    <xs:sequence>

                                        <xs:element name="autor" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:group ref="saps:student"/>
                                            </xs:complexType>
                                        </xs:element>

                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="data" type="xs:dateTime"/>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="ciało">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="lista_sklepów">
                                <xs:complexType>
                                    <xs:sequence>

                                        <xs:element name="sklep" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="nazwa" type="xs:string" use="required"/>
                                                <xs:attribute name="id" type="saps:id_xxxx" use="required"/>
                                                <xs:attribute name="URI" type="xs:anyURI" use="optional"/>
                                            </xs:complexType>
                                        </xs:element>

                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="lista_dysków">
                                <xs:complexType>
                                    <xs:sequence>

                                        <xs:element name="dysk" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>

                                                    <xs:element name="marka" type="xs:string"/>
                                                    <xs:element name="model" type="xs:string"/>
                                                    <xs:element name="pojemność" type="saps:pojemność"/>
                                                    <xs:element name="cena" type="saps:cena"/>
                                                    <xs:element name="ocena" type="saps:ocena"/>

                                                </xs:sequence>
                                                <xs:attribute name="typ" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="SSD"/>
                                                            <xs:enumeration value="HDD"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                                <xs:attribute name="id" type="saps:id_xxxx" use="required"/>
                                                <xs:attribute name="sklep" type="xs:IDREF" use="required"/>
                                            </xs:complexType>
                                        </xs:element>

                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>

        <xs:key name="sklep_key">
            <xs:selector xpath="ciało/fdgd/sklep"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:keyref name="sklep_ref" refer="saps:sklep_key">
            <xs:selector xpath="ciało/lista_dysków/dysk"/>
            <xs:field xpath="@sklep"/>
        </xs:keyref>

    </xs:element>


    <xs:simpleType name="id_xxxx">
        <xs:restriction base="xs:ID">
            <xs:length value="4"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="telefon">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{3}-[0-9]{3}-[0-9]{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="email">
        <xs:restriction base="xs:string">
            <xs:pattern
                    value="([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="plec">
        <xs:restriction base="xs:string">
            <xs:pattern value="[MK]"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="wiek">
        <xs:restriction base="xs:positiveInteger"/>
    </xs:simpleType>

    <xs:simpleType name="numer_indeksu">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{6}"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:complexType name="cena">
        <xs:simpleContent>
            <xs:extension base="xs:decimal">
                <xs:attribute name="waluta">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="USD"/>
                            <xs:enumeration value="PLN"/>
                            <xs:enumeration value="EUR"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="ocena">
        <xs:restriction base="xs:decimal">
            <xs:pattern value="[1-5].0|[1-4].5"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="pojemność">
        <xs:simpleContent>
            <xs:extension base="xs:positiveInteger">
                <xs:attribute name="jednostka">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="GB"/>
                            <xs:enumeration value="TB"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>


    <xs:group name="student">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="imię" type="xs:string"/>
            <xs:element name="nazwisko" type="xs:string"/>
            <xs:element name="numer_indeksu" type="saps:numer_indeksu" minOccurs="0"/>
        </xs:sequence>
    </xs:group>


</xs:schema>

=== AGranosik/pkck/Zadanie5/xml-parser/xml/lista_dysków.xml
<?xml version="1.0" encoding="UTF-8"?>
<dokument
        xmlns="http://example.com/saps"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://example.com/saps lista_dysków.xsd">

    <nagłówek>
        <autorzy>
            <autor>
                <imię>Piotr</imię>
                <nazwisko>Stańczyk</nazwisko>
                <numer_indeksu>203999</numer_indeksu>
            </autor>
            <autor>
                <imię>Szymon</imię>
                <nazwisko>Adach</nazwisko>
                <numer_indeksu>203844</numer_indeksu>
            </autor>
        </autorzy>
        <data>2018-06-06T19:06:54.446+02:00</data>
    </nagłówek>

    <ciało>
        <lista_sklepów>
            <sklep URI="https://www.morele.net" nazwa="Morele" id="s001"/>
            <sklep nazwa="Media Markt" id="s002"/>
            <sklep nazwa="Media Expert" id="s003"/>
            <sklep nazwa="Komputronik" id="s004"/>
            <sklep nazwa="RTV Euro AGD" id="s005"/>
            <sklep nazwa="x-kom" id="s006"/>
        </lista_sklepów>
        <lista_dysków>
            <dysk typ="SSD" sklep="s001" id="d001">
                <marka>Crucial</marka>
                <model>MX200</model>
                <pojemność jednostka="GB">240</pojemność>
                <cena waluta="EUR">299.99</cena>
                <ocena>4.5</ocena>
            </dysk>
            <dysk typ="SSD" sklep="s002" id="d002">
                <marka>Micron</marka>
                <model>M1100</model>
                <pojemność jednostka="GB">250</pojemność>
                <cena waluta="PLN">249.99</cena>
                <ocena>4.5</ocena>
            </dysk>
            <dysk typ="HDD" sklep="s003" id="d003">
                <marka>Seagate</marka>
                <model>Expansion Portable</model>
                <pojemność jednostka="TB">1</pojemność>
                <cena waluta="EUR">189.99</cena>
                <ocena>4.5</ocena>
            </dysk>
            <dysk typ="SSD" sklep="s004" id="d004">
                <marka>ADATA</marka>
                <model>Ultimate SU800</model>
                <pojemność jednostka="GB">256</pojemność>
                <cena waluta="PLN">304.99</cena>
                <ocena>5.0</ocena>
            </dysk>
            <dysk typ="HDD" sklep="s004" id="d005">
                <marka>Seagate</marka>
                <model>Expansion Desktop</model>
                <pojemność jednostka="TB">2</pojemność>
                <cena waluta="PLN">254.79</cena>
                <ocena>4.5</ocena>
            </dysk>
            <dysk typ="SSD" sklep="s006" id="d006">
                <marka>Toshiba</marka>
                <model>Canvio Basics</model>
                <pojemność jednostka="TB">1</pojemność>
                <cena waluta="PLN">195.55</cena>
                <ocena>5.0</ocena>
            </dysk>
            <dysk typ="SSD" sklep="s005" id="d007">
                <marka>ADATA</marka>
                <model>Ultimate SU800</model>
                <pojemność jednostka="GB">128</pojemność>
                <cena waluta="PLN">179.88</cena>
                <ocena>5.0</ocena>
            </dysk>
            <dysk typ="SSD" sklep="s002" id="d008">
                <marka>ADATA</marka>
                <model>Ultimate SU900</model>
                <pojemność jednostka="GB">256</pojemność>
                <cena waluta="USD">379.47</cena>
                <ocena>5.0</ocena>
            </dysk>
            <dysk typ="SSD" sklep="s003" id="d009">
                <marka>GOODRAM</marka>
                <model>IRIDIUM PRO</model>
                <pojemność jednostka="GB">240</pojemność>
                <cena waluta="PLN">399.99</cena>
                <ocena>4.5</ocena>
            </dysk>
            <dysk typ="HDD" sklep="s003" id="d010">
                <marka>Seagate</marka>
                <model>Barracuda</model>
                <pojemność jednostka="TB">1</pojemność>
                <cena waluta="PLN">173.88</cena>
                <ocena>4.5</ocena>
            </dysk>
            <dysk typ="SSD" sklep="s002" id="d011">
                <marka>Samsung</marka>
                <model>850 EVO</model>
                <pojemność jednostka="GB">500</pojemność>
                <cena waluta="PLN">525.00</cena>
                <ocena>5.0</ocena>
            </dysk>
            <dysk typ="SSD" sklep="s006" id="d012">
                <marka>Samsung</marka>
                <model>850 EVO</model>
                <pojemność jednostka="GB">250</pojemność>
                <cena waluta="PLN">319.00</cena>
                <ocena>5.0</ocena>
            </dysk>
            <dysk typ="SSD" sklep="s006" id="d013">
                <marka>GOODRAM</marka>
                <model>CX300</model>
                <pojemność jednostka="GB">120</pojemność>
                <cena waluta="PLN">151.40</cena>
                <ocena>4.5</ocena>
            </dysk>
            <dysk typ="SSD" sklep="s004" id="d014">
                <marka>Samsung</marka>
                <model>960 EVO</model>
                <pojemność jednostka="GB">250</pojemność>
                <cena waluta="USD">509.00</cena>
                <ocena>5.0</ocena>
            </dysk>
            <dysk typ="SSD" sklep="s004" id="d015">
                <marka>Crucial</marka>
                <model>MX500</model>
                <pojemność jednostka="GB">250</pojemność>
                <cena waluta="PLN">309.98</cena>
                <ocena>5.0</ocena>
            </dysk>
            <dysk typ="SSD" sklep="s001" id="d016">
                <marka>Crucial</marka>
                <model>MX500</model>
                <pojemność jednostka="GB">500</pojemność>
                <cena waluta="PLN">514.54</cena>
                <ocena>5.0</ocena>
            </dysk>
            <dysk typ="HDD" sklep="s001" id="d017">
                <marka>Toshiba</marka>
                <model>P300</model>
                <pojemność jednostka="TB">1</pojemność>
                <cena waluta="PLN">154.86</cena>
                <ocena>5.0</ocena>
            </dysk>
            <dysk typ="SSD" sklep="s002" id="d018">
                <marka>GOODRAM</marka>
                <model>IRDM</model>
                <pojemność jednostka="GB">120</pojemność>
                <cena waluta="USD">174.08</cena>
                <ocena>4.5</ocena>
            </dysk>
            <dysk typ="SSD" sklep="s005" id="d019">
                <marka>GOODRAM</marka>
                <model>IRDM</model>
                <pojemność jednostka="GB">240</pojemność>
                <cena waluta="USD">298.98</cena>
                <ocena>5.0</ocena>
            </dysk>
            <dysk typ="HDD" sklep="s003" id="d020">
                <marka>WD</marka>
                <model>Elements Portable</model>
                <pojemność jednostka="TB">2</pojemność>
                <cena waluta="PLN">308.98</cena>
                <ocena>5.0</ocena>
            </dysk>
            <dysk typ="HDD" sklep="s004" id="d021">
                <marka>Maxtor</marka>
                <model>M3 Portable</model>
                <pojemność jednostka="TB">1</pojemność>
                <cena waluta="PLN">188.79</cena>
                <ocena>5.0</ocena>
            </dysk>
        </lista_dysków>
    </ciało>

</dokument>
